name: glfw
version: 1.0.2
description: Dart GLFW bindings
authors:
  - John McDole <codefu@google.com>
  - Jason Daly <dalyj@google.com>
  - Michael McLennan <nefario@google.com>
  - Harry Stern <hstern@google.com>
homepage:
environment:
  sdk: ">=2.0.0-dev.36.0 <3.0.0"
dev_dependencies:
  path: "^1.3.9"
  quiver: ">=0.25.0"
