name: glfw
version: "1.0.0"
description: Dart GLFW bindings
author: Harry Stern <hstern@google.com>
homepage:
environment:
  sdk: ">=1.10.0"
dev_dependencies:
  ccompile: "^0.2.10"
  path: "^1.3.9"
  quiver: ">=0.25.0"
